kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: dockerhub
  creationTimestamp: null
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  labels:
    codefresh.io/entity: integration-secret
    codefresh.io/integration-name: dockerhub
    codefresh.io/integration-type: registry.dockerhub
spec:
  template:
    metadata:
      name: dockerhub
      creationTimestamp: null
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
  encryptedData:
    password: >-
      AgCKTpCDwCPUiQSqWWyPrRSzIpgtRL5uCX/mRRegdB6tna2nJSzu2gRdEZ6mZd+87vT0bvo7qZxIqmlzpA1h9uqjvDMBzTg0lNmIjnU1FZ07gsktjPg2Xpaf1UZURaac5MQNVKSo7hDd/gKo9E291i1eBETCVZPiu29RTg7G/7tKIbPOXL8BXMKXQIAgylqGa12sVa1+Ic6BnoMmCtKQuhB2QBw7JHHPdLCwlKe+WdpIgqdVQ1lG4HlusSyuNkGH3441BF9h/RzlR77DxgtZJSVwkgfHolfb9C5j7G3yR0+U9qYzASkj3e84q0qKR8iOfWVUJRcVi3He9zpJ6Ee0r0ogdpaxzek/Qs3HWqoevwttUR+PBDIvsC8ed1TNt242jqfbUpwY7oEo6mXyv9PI/0fveGRdfP9P+0ns2XtT1/gGJHCx2Wub+t2ZP9V4stmr4kNKl+I/87cHh75erUTw2PC6fRyT/kE0GxxuRLklWhsW9fPBZOFNwGJyJk80c6nUgiE0xnSimPCF88eJowsf+FQWlvW77HgmXBvCweru8Bps0JvVXk67OhuYsZ+Rcm0m6f1FyQYZBrD2gPxRL34Sx1t5/UzyMBJWOsc/2lcKls0Qc4Hl3qGxlJ/ThdY07ntmvbQ9wdPpnVMHc3fZNCvxT615fgHKv+cMqraPSYqt4ebI0Bf7H1wZzE7MRnWARLVHwBKG+1W1b16/9Uo=
