apiVersion: v1
kind: ConfigMap
metadata:
  name: test-connection
  labels:
    codefresh.io/entity: integration-config
    codefresh.io/integration-type: registry.ecr
data:
  region: us-east-2
  role_arn: arn:aws:iam::882458141806:role/andrii-ecr
