apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: local51
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/local51/*.yaml,runtimes/local51/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml,ecr/integration.config.yaml,ecr-static/integration.secret.yaml,ecr-static/integration.config.yaml,ecr1-static/integration.config.yaml,ecr1-static/integration.secret.yaml}
      recurse: true
    path: shared-config/resources
    repoURL: https://github.com/andrii-codefresh/local51.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
